In [7]:
import torch

In [8]:
file = "encoder.pt" # 4 слоя нейронной сети с 2мя полносвязными слоями и нормализацией
encode1 = torch.load(file)
encode1

OrderedDict([('mlp1.fc1.weight',
              tensor([[-0.1327, -0.0720,  0.0125,  ...,  0.0937,  0.0609,  0.1147],
                      [ 0.0191, -0.0743,  0.2280,  ..., -0.0073, -0.1859,  0.0084],
                      [-0.1344,  0.1321,  0.0737,  ...,  0.1499, -0.0102, -0.2651],
                      ...,
                      [-0.0665,  0.0482, -0.1542,  ...,  0.0203, -0.1666, -0.1739],
                      [-0.0568,  0.1252,  0.0274,  ..., -0.2134,  0.0047,  0.0081],
                      [ 0.0277, -0.0285, -0.0808,  ..., -0.1234, -0.0390, -0.0548]],
                     device='cuda:0')),
             ('mlp1.fc1.bias',
              tensor([ 0.1366,  0.0479,  0.1633,  0.1037,  0.0570,  0.0036,  0.1143,  0.0640,
                       0.0421,  0.1055,  0.0831,  0.1061,  0.1050,  0.0724,  0.0946,  0.0966,
                       0.1431, -0.0269,  0.1332,  0.0416,  0.1201,  0.0634,  0.0824,  0.2189,
                       0.1427,  0.0409,  0.0959,  0.0649,  0.0361,  0.1117,  0.036

In [9]:
file2 = "encoder-Copy1.pt" # 4 слоя нейронной сети с 2мя полносвязными слоями и нормализацией
encode2 = torch.load(file2)
encode2

OrderedDict([('mlp1.fc1.weight',
              tensor([[-0.0985, -0.0611,  0.0108,  ...,  0.0767,  0.0536,  0.1108],
                      [ 0.0300, -0.1031,  0.1852,  ..., -0.0171, -0.1900,  0.0475],
                      [-0.1137,  0.0941,  0.0119,  ...,  0.1607, -0.0046, -0.2495],
                      ...,
                      [-0.0557,  0.0134, -0.1334,  ..., -0.0152, -0.1745, -0.1526],
                      [ 0.0428,  0.1181,  0.0613,  ..., -0.2109,  0.0081, -0.0174],
                      [-0.0130, -0.0295, -0.0744,  ..., -0.0959, -0.0474, -0.0806]],
                     device='cuda:0')),
             ('mlp1.fc1.bias',
              tensor([0.1030, 0.0970, 0.0970, 0.0969, 0.1030, 0.0970, 0.0970, 0.1030, 0.0970,
                      0.0972, 0.1030, 0.0970, 0.0970, 0.0969, 0.1030, 0.1030, 0.0970, 0.0970,
                      0.1030, 0.0970, 0.0970, 0.1029, 0.1030, 0.1030, 0.0970, 0.0970, 0.1030,
                      0.1030, 0.1030, 0.0968, 0.1030, 0.1030, 0.1030, 0.1030, 0.09