In [1]:
import torch

In [4]:
file = "decoder.pt"
torch.load(file)

OrderedDict([('msg_fc1.0.weight',
              tensor([[ 0.2003,  0.1704,  0.0466,  ...,  0.1205,  0.3381,  0.3044],
                      [-0.3029, -0.0340,  0.0972,  ...,  0.2124, -0.2016,  0.1221],
                      [-0.3334,  0.3001, -0.2483,  ...,  0.0197,  0.2548, -0.2474],
                      ...,
                      [-0.0229,  0.1453, -0.2323,  ..., -0.1166, -0.0822,  0.1030],
                      [-0.3562,  0.3886,  0.0576,  ..., -0.3360, -0.1266, -0.0698],
                      [ 0.1320,  0.3034,  0.2244,  ..., -0.2443,  0.0604,  0.0811]],
                     device='cuda:0')),
             ('msg_fc1.0.bias',
              tensor([-1.1937e-01,  1.8822e-02, -1.4320e-04, -3.6069e-03,  3.2434e-01,
                       1.7983e-01,  1.1908e-02, -1.5069e-01, -1.7567e-01, -3.0180e-01,
                      -2.8479e-01,  2.2480e-01, -1.5480e-01,  1.5437e-01,  1.7379e-01,
                      -3.0228e-01,  6.2846e-02, -1.0775e-01, -7.0320e-02, -2.2960e-01,
              

In [11]:
file = "encoder.pt" # 4 слоя нейронной сети с 2мя полносвязными слоями и нормализацией
encode = torch.load(file)

In [10]:
import pickle

with open('metadata.pkl', 'rb') as f:
    data = pickle.load(f)
data

{'args': Namespace(batch_size=128, cuda=True, decoder='mlp', decoder_dropout=0.0, decoder_hidden=256, dims=4, dynamic_graph=False, edge_types=2, encoder='mlp', encoder_dropout=0.0, encoder_hidden=256, epochs=5, factor=True, gamma=0.5, hard=False, load_folder='', lr=0.0005, lr_decay=200, no_cuda=False, no_factor=False, num_atoms=5, prediction_steps=10, prior=False, save_folder='logs', seed=42, skip_first=False, suffix='_springs5', temp=0.5, timesteps=49, var=5e-05)}

In [12]:
encode

OrderedDict([('mlp1.fc1.weight',
              tensor([[-0.0534, -0.0314,  0.0291,  ..., -0.0074,  0.0752,  0.1167],
                      [ 0.0162,  0.0562, -0.0257,  ...,  0.0363, -0.0153, -0.0795],
                      [ 0.0798, -0.0741,  0.0985,  ...,  0.0813, -0.0198, -0.1198],
                      ...,
                      [ 0.0050, -0.0926,  0.0071,  ..., -0.0288,  0.0383, -0.0709],
                      [-0.0781, -0.0744,  0.0840,  ...,  0.0026, -0.0907,  0.0442],
                      [-0.1559,  0.0301,  0.0567,  ..., -0.0166, -0.0752,  0.0409]],
                     device='cuda:0')),
             ('mlp1.fc1.bias',
              tensor([0.1123, 0.1417, 0.1014, 0.1213, 0.1276, 0.1064, 0.0949, 0.0671, 0.0999,
                      0.1111, 0.1114, 0.0883, 0.0908, 0.0397, 0.0843, 0.0876, 0.0856, 0.0845,
                      0.1100, 0.0951, 0.1314, 0.0927, 0.0838, 0.0993, 0.1083, 0.1051, 0.0944,
                      0.0670, 0.1132, 0.0978, 0.1248, 0.0976, 0.0950, 0.1213, 0.12

In [16]:
from utils import *
from modules import *

ModuleNotFoundError: No module named 'utils'